### ISSUE TITLE
jetpackrelated中Room数据库问题

### ISSUE THREAD

**Issue by mxdlsm** [zhangnangua/grocery-store#1]
大佬您好，仿照您的room案列使用，为什么把kotlin版本升到1.7.0就报错
错误: Type of the parameter must be a class annotated with @Entity or a collection/array of it.
kotlin.coroutines.Continuation<? super kotlin.Unit> continuation);
去掉Dao中的suspend就好了。这是为什么？如何不去掉suspend解决这个报错？

**Comment by zhangnangua** [comment]
升级room版本至  2.4.2

`    
    def room_version = "2.4.2"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
`

**Comment by mxdlsm** [comment]
我现在就是2.4.2哈哈，把kotlin版本降低1.6.10就好用，不知道为什么
